name             'base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures base'
long_description 'Installs/Configures base'
version          '0.1.0'

depends 'hostnames'
depends 'postfix'
depends 'apt-periodic'
depends 'aide'
depends 'clamav'
depends 'dnsupdate'
